-- ***********CREATE TABLES***********

-- table example:
    -- id: 1
    -- csduid: 4806016
    -- csd: Ottawa
CREATE TABLE Location (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  csduid VARCHAR2(10) UNIQUE NOT NULL,
  csd VARCHAR2(100) NOT NULL
);

-- table example:
    -- id: 1
    -- name: Housing Type
    -- type: Semi-detached
CREATE TABLE HousingType (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  type VARCHAR2(50) NOT NULL
);

-- table example:
    -- id: 1
    -- location_id: 4
    -- housing_type_id: 3
    -- period: 1988,
    -- indicator_summary: Housing Starts,
    -- unit_of_measure: "" (we have no data for this)
    -- original_value: 784.00000
    -- is_display: Y,
    -- display_order: 0,
CREATE TABLE HousingInfo (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id NUMBER NOT NULL,
  housing_type_id NUMBER NOT NULL,
  period VARCHAR2(4) NOT NULL,
  indicator_summary VARCHAR2(100),
  unit_of_measure VARCHAR2(50),
  original_value NUMBER,
  is_display CHAR(1) CHECK (is_display IN ('Y', 'N')),
  display_order NUMBER,
  FOREIGN KEY (location_id) REFERENCES Location(id),
  FOREIGN KEY (housing_type_id) REFERENCES HousingType(id)
);


-- ***********INSERT DUMMY DATA***********
--Location
INSERT INTO Location (csduid, csd) VALUES ('4808011', 'Red Deer');
INSERT INTO Location (csduid, csd) VALUES ('4806001', 'Calgary');
--Housing Typw
INSERT INTO HousingType (name, type) VALUES ('Housing Type', 'Apartment');
INSERT INTO HousingType (name, type) VALUES ('Housing Type', 'Semi-detached');
INSERT INTO HousingType (name, type) VALUES ('Housing Type', 'Row');
INSERT INTO HousingType (name, type) VALUES ('Housing Type', 'Single-detached');
INSERT INTO HousingType (name, type) VALUES ('Housing Type', 'Mobile Home');
--Housing Info
INSERT INTO HousingInfo VALUES (DEFAULT, 1, 1, '1987', 'Housing Starts', '', 58.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 1, 1, '1988', 'Housing Starts', '', 24.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 1, 1, '1989', 'Housing Starts', '', 35.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 1, 1, '1990', 'Housing Starts', '', 12.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 1, 1, '1991', 'Housing Starts', '', 0.0,  'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 2, 2, '1987', 'Housing Starts', '', 76.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 2, 2, '1988', 'Housing Starts', '', 64.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 2, 3, '1989', 'Housing Starts', '', 32.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 2, 4, '1990', 'Housing Starts', '', 91.0, 'Y', 0);
INSERT INTO HousingInfo VALUES (DEFAULT, 2, 5, '1991', 'Housing Starts', '', 10.0, 'Y', 0);
